#!/bin/bash
#
#    ___| |__   ___  ___| | __
#   / __| '_ \ / _ \/ __| |/ /
#  | (__| | | |  __/ (__|   <
#   \___|_| |_|\___|\___|_|\_\
#
# check - Quickly spell-check and correct text from the terminal with aspell
# Requirements: 
#
# Project: https://github.com/galaxy-cli/check

# --- DEPENDENCY CHECK ---
missing=()
for cmd in xsel aspell; do
    if ! command -v "$cmd" >/dev/null 2>&1; then
        missing+=("$cmd")
    fi
done

if [ "${#missing[@]}" -gt 0 ]; then
    echo "check: error: The following dependencies are missing: ${missing[*]}" >&2
    read -rp "Would you like to install them via apt? [Y/n] " yn
    yn=${yn:-Y}

    if [[ $yn =~ ^[Yy]$ ]]; then
        sudo apt update && sudo apt install -y "${missing[@]}"
    else
        echo "check: error: cannot continue without required dependencies" >&2
        exit 1
    fi
fi

# --- USAGE ---
print_usage() {
    cat <<EOF
USAGE
  check
  check FILE
  check [OPTION]
OPTION
  --clipboard   Use clipboard to spell check (xsel)
  --cursor      Uses cursor hightlighted text to spell check
EOF
}

temp=$(mktemp)
trap 'rm -f "$temp"' EXIT

# --- CHECK INPUT ---
# `check`
input_from_user() {
    echo "Enter text (Press Ctrl+D when finished):"
    echo "----- BEFORE -----"
    cat > "$temp"
    if [[ ! -s "$temp" ]] || ! grep -q "[^[:space:]]" "$temp"; then
        exit 1
    fi
}

# `check FILE`
input_from_file() {
    local file="$1"
    echo "----- BEFORE -----"
    cat "$file" > "$temp"
    cat "$file"
}

# `check --clipboard`
input_from_clipboard() {
	xsel --clipboard > "$temp"
	if [[ ! -s "$temp" ]]; then
        	echo "No text found in clipboard"
        	exit 1
	fi
	echo "----- BEFORE -----"
	cat "$temp"
	echo
}

# `check --cursor`
input_from_primary() {
	xsel --primary > "$temp"
	if [[ ! -s "$temp" ]]; then
        	echo "check: error: No text found in X11 primary selection (highlighted text)"
        	exit 1
	fi
        echo "----- BEFORE -----"
        cat "$temp"
	echo
}

# --- OPTION ---
case "$1" in
    --help)
        print_usage
        exit 0
        ;;
    --clipboard)
        input_from_clipboard
        ;;
    --cursor)
        input_from_primary
        ;;
    "")
        input_from_user
        ;;
    *)
        if [[ -f "$1" ]]; then
            input_from_file "$1"
        else
            echo "$*" > "$temp"
            echo "----- BEFORE -----"
            echo "$*"
        fi
        ;;
esac

# --- CHECK OUTPUT ---
aspell -c "$temp"
echo "----- AFTER ------"
cat "$temp"